# Generated by Django 3.2.4 on 2021-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211115_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('Aadhar', models.ImageField(default='', upload_to='base/images')),
                ('DOB', models.DateField()),
                ('phone', models.IntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Father_Husband_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Birth_place', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
    ]
