# Generated by Django 3.2.4 on 2021-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_phone_consultant_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='Aadhar',
            field=models.CharField(max_length=12),
        ),
    ]
